image: openjdk:8-jdk

variables:
  ANDROID_SDK_URL: "https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip"

cache:
  key: $CI_PROJECT_PATH_SLUG
  paths:
    - .gradle/wrapper
    - .gradle/caches

before_script:
  - export GRADLE_USER_HOME="`pwd`/.gradle"
  - export ANDROID_HOME="`pwd`/android-sdk-linux"
  - export PATH=$PATH:$ANDROID_HOME/emulator:$ANDROID_HOME/platform-tools:$ANDROID_HOME/tools/bin
  - apt-get --quiet update --yes
  - apt-get --quiet install --yes wget tar unzip lib32stdc++6 lib32z1
  - wget --quiet --output-document=android-sdk.tgz "$ANDROID_SDK_URL"
  - mkdir -p android-sdk-linux
  - unzip -x android-sdk.tgz -d "$ANDROID_HOME"
  - echo y | sdkmanager $(<.android-packages) > /dev/null

stages:
  - build
  - test

build:
  stage: build
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
    - app/build/outputs/

unitTests:
  stage: test
  script:
    - ./gradlew test

functionalTests:
  stage: test
  script:
    - apt install -y libqt5widgets5
    - wget --quiet --output-document=android-wait-for-emulator https://raw.githubusercontent.com/travis-ci/travis-cookbooks/0f497eb71291b52a703143c5cd63a217c8766dc9/community-cookbooks/android-sdk/files/default/android-wait-for-emulator
    - chmod +x android-wait-for-emulator
    - echo y | sdkmanager $(<.android-packages-emulator) > /dev/null
    - emulator64-x86 -avd test -no-window -no-audio
    - ./android-wait-for-emulator
    - adb shell input keyevent 82
    - ./gradlew cAT
